---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Magma
    language: magma
    name: magma
---

### Finding power series expansions along exceptional components
------------------------------------------------------------------------------------------
First we define the surface, for now only in affine form. This is the surface Wittenberg works with in his article

```{magma}
A3<x,y,t>:=AffineSpace(Rationals(),3);
p:=3*(t-1)^3*(t+3);
q:=Evaluate(p,[x,y,-t]);
F:=y^2-x*(x-p)*(x-q);
E:=Surface(A3,F);
```

We also must compute the equations for $E$ on the affine patch about infinity.

```{magma}
p_inf:=3*(1-t)^3*(1+3*t);
q_inf:=3*(-1-t)^3*(-1+3*t);
F_inf:=y^2-x*(x-p_inf)*(x-q_inf);
E_inf:=Surface(A3, F_inf);
```

We check the discriminant of the elliptic curve. We need to do some hacky algebra to extract the polynomial we're interested in.

```{magma}
Factorization(Discriminant(F-y^2,x));
Factorization(Discriminant(F_inf-y^2,x));
```

Singular subscheme, and some of the points in the support

```{magma}
Support(SingularSubscheme(E));
Support(SingularSubscheme(E_inf));
```

```{magma}
Etilde:=DesingulariseSurfaceByBlowUp(E);
Etilde_inf:=DesingulariseSurfaceByBlowUp(E_inf);
```

### Residue formula


Given a complete local DVR $R$ with uniformizer $\pi$ and residue field $k$, we compute the residue of a quaternion algebra $(f,g)$ as the class of $(-1)^{v(f)v(g)}\widetilde{f}^{v(g)}\widetilde{g}^{v(f)}$ in $k^*/k^{*2}$ where for any $h\in R$ we define $\widetilde{h}=h\pi^{-v(h)}$.

```{magma}
function ComputeResidue(f, g)
    vf:=Valuation(f);
    vg:=Valuation(g);
    
    f_0:=Coefficients(f)[1];
    g_0:=Coefficients(g)[1];
    
    return f_0^(vg)*g_0^(vf)*(-1)^(vf*vg);
end function;

function IsSquareQU(f)
    R := PolynomialRing(Integers());
    return IsSquare(R ! Numerator(f)) and IsSquare(R ! Denominator(f));
end function;

function ComputeAllInterestingResidues(X, Y, T, IsInf)
    if IsInf then
        PT := 3*(1-T)^3*(1+3*T);
        QT := 3*(-1-T)^3*(-1+3*T);
    else
        PT := 3*(T-1)^3*(T+3);
        QT := 3*(-T-1)^3*(-T+3);
    end if;
    Glist := [X-PT, X-QT];
    Flist := [T, T+1, T-1, T+3, T-3];
    return [ComputeResidue(f,g) : f in Flist, g in Glist];
end function;
```

### Computing list of residues for all bad fibers

```{magma}


```

### Computing residue at ((-9, 0), 0) 


#### Component 1


We unpack some of the desingularization data here. We pick one exceptional component L on a patch Y of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
A2<x2,y2>:=AffinePlane(Rationals());
L:=Curve(A2, Evaluate(DefiningPolynomial(E), [x2,y2,0]));
L;
```

We define a rational function field that we use to parametrize the exceptional component L with

```{magma}
Q<U>:=FunctionField(Rationals(), 1);
R<y>:=PolynomialRing(Q);
kU<a>:=quo<R | y^2-U>;
```

We write down a parametrization of L and check that it satisfies that parametrization. In particular, we see that "V" on Y vanishes on L (we'll see we can use it as a uniformizer at the generic point of L)

```{magma}
Xu:=U;
Yu:=(U+9)*a;
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[Xu,Yu]) eq 0};
```

```{magma}
kUT<Tu>:=PowerSeriesRing(kU);
```

```{magma}
R<Ypol>:=PolynomialRing(kUT);
```

Another assumption: We set W to be the function in U that we need and we solve T as a power series in $k( U)[[V]]$ from the equation that we have. If V were not a valid choice as uniformizer, we'd probably fail to solve this equation at this point. Below we just compute all the roots and take the one close to the expression Tu that we already computed (because we know our series for T should specialize to Tu on L for V=0). It would be better to explicitly use newton iteration with initial approximation Tu.

```{magma}
F:=Evaluate(DefiningPolynomial(E), [Xu, Ypol, Tu]);
Fprime:=Derivative(F);
for i in [1..5] do
    Temp:=Yu-Evaluate(F, Yu)/Evaluate(Fprime,Yu);
    Yu:=Temp;
end for;
```

We verify that the power series in $k(U)[[V]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(E),[Xu,Yu,Tu])+O(Tu^(10));
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $V,W,T$ (apologies for the mess-up in naming here: the two $T$s are not the same), and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

#### Component 2


We unpack some of the desingularization data here. We pick one exceptional component L on a patch Y of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E,Etilde[1],1);
A3<T,V,W>:=Ambient(Y);
```

We define a rational function field that we use to parametrize the exceptional component L with

```{magma}
kU<U>:=FunctionField(Rationals(),1);
```

We write down a parametrization of L and check that it satisfies that parametrization. In particular, we see that "V" on Y vanishes on L (we'll see we can use it as a uniformizer at the generic point of L)

```{magma}
Vu:=3/2*(U^2-1)/U;
Wu:=1/48*(U^2+1)/U;
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[0,Vu,Wu]) eq 0};
```

```{magma}
kUT<Tu>:=PowerSeriesRing(kU);
```

```{magma}
R<Wpol>:=PolynomialRing(kUT);
```

Another assumption: We set W to be the function in U that we need and we solve T as a power series in $k( U)[[V]]$ from the equation that we have. If V were not a valid choice as uniformizer, we'd probably fail to solve this equation at this point. Below we just compute all the roots and take the one close to the expression Tu that we already computed (because we know our series for T should specialize to Tu on L for V=0). It would be better to explicitly use newton iteration with initial approximation Tu.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Tu, Vu, Wpol]);
Fprime:=Derivative(F);
for i in [1..4] do
    Temp:=Wu-Evaluate(F, Wu)/Evaluate(Fprime,Wu);
    Wu:=Temp;
end for;
```

We verify that the power series in $k(U)[[V]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Tu,Vu,Wu])+O(Tu^(10));
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $V,W,T$ (apologies for the mess-up in naming here: the two $T$s are not the same), and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Tu, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Tu, Vu, Wu]);
Tu:=Evaluate(DefiningPolynomials(pi)[3], [Tu, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

### Computing residue at ((0, 0), -3) 


#### Component 1


We unpack some of the desingularization data here. We pick one exceptional component L on a patch Y of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
A2<x2,y2>:=AffinePlane(Rationals());
L:=Curve(A2, Evaluate(DefiningPolynomial(E), [x2,y2,-3]));
L;
```

We define a rational function field that we use to parametrize the exceptional component L with

```{magma}
Q<U>:=FunctionField(Rationals(), 1);
R<y>:=PolynomialRing(Q);
kU<a>:=quo<R | y^2-U+144>;
```

We write down a parametrization of L and check that it satisfies that parametrization. In particular, we see that "V" on Y vanishes on L (we'll see we can use it as a uniformizer at the generic point of L)

```{magma}
Xu:=U;
Yu:=U*a;
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[Xu,Yu]) eq 0};
```

```{magma}
kUV<Vu>:=PowerSeriesRing(kU);
Tu:=Vu-3;
```

```{magma}
R<Ypol>:=PolynomialRing(kUV);
```

Another assumption: We set W to be the function in U that we need and we solve T as a power series in $k( U)[[V]]$ from the equation that we have. If V were not a valid choice as uniformizer, we'd probably fail to solve this equation at this point. Below we just compute all the roots and take the one close to the expression Tu that we already computed (because we know our series for T should specialize to Tu on L for V=0). It would be better to explicitly use newton iteration with initial approximation Tu.

```{magma}
F:=Evaluate(DefiningPolynomial(E), [Xu, Ypol, Tu]);
Fprime:=Derivative(F);
for i in [1..3] do
    Temp:=Yu-Evaluate(F, Yu)/Evaluate(Fprime,Yu);
    Yu:=Temp;
end for;
```

We verify that the power series in $k(U)[[V]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(E),[Xu,Yu,Tu])+O(Vu^(5));
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $V,W,T$ (apologies for the mess-up in naming here: the two $T$s are not the same), and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

#### Component 2


We now pick the exceptional component L on the patch Y over $((0, 0), -3)$ of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E,Etilde[2],1);
A3<X,V,W>:=Ambient(Y);
```

We define a rational function field that we use to parametrize the exceptional component L with

```{magma}
kU<U>:=FunctionField(Rationals(),1);
```

We write down a parametrization of L and check that it satisfies that parametrization. In particular, we see that "V" on Y vanishes on L (we'll see we can use it as a uniformizer at the generic point of L)

```{magma}
L;
```

Below we find a parametrization of $L$.

```{magma}
Lc,phiL:=Conic(ProjectiveClosure(L));
piL:=Parametrization(Lc);
Q<x, v, w>:=FunctionField(L);
kU<U>:=FunctionField(Domain(piL));
Vu:=Pullback(piL, Pullback(Inverse(phiL), v));
Wu:=Pullback(piL, Pullback(Inverse(phiL), w));
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[0,Vu,Wu]) eq 0};
Vu;
Wu;
```

```{magma}
kUX<Xu>:=PowerSeriesRing(kU);
```

```{magma}
R<Wpol>:=PolynomialRing(kUX);
```

Another assumption: We set W to be the function in U that we need and we solve T as a power series in $k( U)[[V]]$ from the equation that we have. If V were not a valid choice as uniformizer, we'd probably fail to solve this equation at this point. Below we just compute all the roots and take the one close to the expression Tu that we already computed (because we know our series for T should specialize to Tu on L for V=0). It would be better to explicitly use newton iteration with initial approximation Tu.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Xu, Vu, Wpol]);
Fprime:=Derivative(F);
for i in [1..4] do
    Temp:=Wu-Evaluate(F, Wu)/Evaluate(Fprime,Wu);
    Wu:=Temp;
end for;
```

We verify that the power series in $k(U)[[V]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Xu,Vu,Wu])+O(Xu^8);
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $V,W,T$ (apologies for the mess-up in naming here: the two $T$s are not the same), and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Xu, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Xu, Vu, Wu]);
Tu:=Evaluate(DefiningPolynomials(pi)[3], [Xu, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

### Computing residues at ((0, 0), -1) 


#### Component 1


We unpack some of the desingularization data here. We pick one exceptional component L on a patch Y of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
A2<x2,y2>:=AffinePlane(Rationals());
L:=Curve(A2, Evaluate(DefiningPolynomial(E), [x2,y2,-1]));
```

We define a rational function field that we use to parametrize the exceptional component L with

```{magma}
Q<U>:=FunctionField(Rationals(), 1);
R<y>:=PolynomialRing(Q);
kU<a>:=quo<R | y^2-U-48>;
```

We write down a parametrization of L and check that it satisfies that parametrization. In particular, we see that "V" on Y vanishes on L (we'll see we can use it as a uniformizer at the generic point of L)

```{magma}
Xu:=U;
Yu:=U*a;
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[Xu,Yu]) eq 0};
```

```{magma}
kUV<Vu>:=PowerSeriesRing(kU);
Tu:=Vu-1;
```

```{magma}
R<Ypol>:=PolynomialRing(kUV);
```

Another assumption: We set W to be the function in U that we need and we solve T as a power series in $k( U)[[V]]$ from the equation that we have. If V were not a valid choice as uniformizer, we'd probably fail to solve this equation at this point. Below we just compute all the roots and take the one close to the expression Tu that we already computed (because we know our series for T should specialize to Tu on L for V=0). It would be better to explicitly use newton iteration with initial approximation Tu.

```{magma}
F:=Evaluate(DefiningPolynomial(E), [Xu, Ypol, Tu]);
Fprime:=Derivative(F);
for i in [1..3] do
    Temp:=Yu-Evaluate(F, Yu)/Evaluate(Fprime,Yu);
    Yu:=Temp;
end for;
```

We verify that the power series in $k(U)[[V]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(E),[Xu,Yu,Tu])+O(Vu^(5));
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $V,W,T$ (apologies for the mess-up in naming here: the two $T$s are not the same), and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

#### Patch 1


Here we pick the component L on the first affine patch Y over $((0,0),-1)$ of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E,Etilde[3],1);
```

Looking at the equation of $L$ we note that it has no rational points and is geometrically reducible. This means that the residue field $k(L)$ will be of the form $k(u)$ with $k$ some finite extension of $\mathbb{Q}$; in our case $k=\mathbb{Q}(\sqrt{48})=\mathbb{Q}(\sqrt{3})$.

```{magma}
A3<X,V,W>:=Ambient(Y);
L;
```

Note that $L:V^2-48=0, X=0$ has no rational points and is geometrically reducible. In particular, one can work out that the residue field is $\kappa(L)=k(W)$ where $k=\mathbb{Q}(a)$ and $a$ is a square root of $3$. Below we define the extension $k/\mathbb{Q}$ as well as a rational function field that we will use to parametrize the exceptional component L with.

```{magma}
k<a>:=QuadraticField(48);
kU<U>:=FunctionField(k,1);
Wu:=U;
```

```{magma}
kUX<Xu>:=PowerSeriesRing(kU);
```

```{magma}
R<Vpol>:=PolynomialRing(kUX);
```

By definition we have an expression for $X$ and $W$ in $k(U)(Xu)$ as $W=U$ and $X=Xu$. It remains to find an expansion for $V$. From our observations above we note that when taking residues $\overline{V}=4a=4\sqrt{3}\in k(W)$, as we mod out by $V^2-48$, and so we have a first order approximation. Applying Newton iteration gives us enough terms to compute residues.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Xu, Vpol, Wu]);
Fprime:=Derivative(F);
Vu:=4*a;
for i in [1..4] do
    Temp:=Vu-Evaluate(F, Vu)/Evaluate(Fprime,Vu);
    Vu:=Temp;
end for;
```

We verify that the power series $Xu,Vu,Wu$ in $k(U)[[Xu]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Xu,Vu,Wu])+O(Xu^10);
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $X,V,W$, and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Xu, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Xu, Vu, Wu]);
Tu:=Evaluate(DefiningPolynomials(pi)[3], [Xu, Vu, Wu]);
```

We now compute power series for our desired functions $X-p(T), X-q(T), 6T(T+1), 6T(T-1)$ in order to compute residues.

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

#### Patch 2


Here we pick the component L on the second affine patch Y over $(0,0,-1)$ of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E,Etilde[3],2);
```

Looking at the equation of $L$ we note that it has no rational points and is geometrically reducible. This means that the residue field $k(L)$ will be of the form $k(u)$ with $k$ some finite extension of $\mathbb{Q}$; in our case $k=\mathbb{Q}(\sqrt{48})=\mathbb{Q}(\sqrt{3})$.

```{magma}
A3<X,V,W>:=Ambient(Y);
L;
```

We define the extension $k/\mathbb{Q}$ as well as a rational function field that we will use to parametrize the exceptional component L with.

```{magma}
k<a>:=QuadraticField(48);
kU<U>:=FunctionField(k,1);
Vu:=U;
```

```{magma}
kUX<Xu>:=PowerSeriesRing(kU);
```

```{magma}
R<Wpol>:=PolynomialRing(kUX);
```

By definition we have an expression for $X$ and $W$ in $k(U)(Xu)$ as $W=U$ and $X=Xu$. It remains to find an expansion for $V$. We note that when taking residues we have $\overline{V}=4a=4\sqrt{3}$, as we mod out by $V^2-48$, and so we have a first order approximation. Applying Newton iteration gives us enough terms to compute residues.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Xu, Vu, Wpol]);
Fprime:=Derivative(F);
Wu:=4*a;
for i in [1..4] do
    Temp:=Wu-Evaluate(F, Wu)/Evaluate(Fprime,Wu);
    Wu:=Temp;
end for;
```

We verify that the power series $Xu,Vu,Wu$ in $k(U)[[Xu]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Xu,Vu,Wu])+O(Xu^10);
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $X,V,W$, and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Xu, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Xu, Vu, Wu]);
Tu:=Evaluate(DefiningPolynomials(pi)[3], [Xu, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

#### Patch 3


Here we pick the component L on the third affine patch Y over $((0,0),-1)$ of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E,Etilde[3],3);
```

```{magma}
A3<T,V,W>:=Ambient(Y);
L;
```

We write down a parametrization of our conic $L$. For the parametrization below we took the projective closure and projected away from the rational point $[0,0,1]$.

```{magma}
kU<U>:=FunctionField(Rationals(), 1);
Vu:=(-6*U^2-1/8)/(-U^2+1/48)-6;
Wu:=-12*U/(-U^2+1/48);
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[-1,Vu,Wu]) eq 0};
```

```{magma}
kUT<Tu>:=PowerSeriesRing(kU);
```

```{magma}
R<Wpol>:=PolynomialRing(kUT);
```

Now we compute an expansion for $W$ in $\mathbb{Q}(U)[[T]]$.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Tu-1, Vu, Wpol]);
Fprime:=Derivative(F);
for i in [1..4] do
    Temp:=Wu-Evaluate(F, Wu)/Evaluate(Fprime,Wu);
    Wu:=Temp;
end for;
```

We verify that the power series $Tu-1,Vu,Wu$ in $k(U)[[Tu]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Tu-1,Vu,Wu])+O(Tu^8);
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $X,V,W$, and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Tu, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Tu, Vu, Wu]);
Tu:=Evaluate(DefiningPolynomials(pi)[3], [Tu, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

### Computing residues at ((0, 0), 1) 


#### Component 1


We unpack some of the desingularization data here. We pick one exceptional component L on a patch Y of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
A2<x2,y2>:=AffinePlane(Rationals());
L:=Curve(A2, Evaluate(DefiningPolynomial(E), [x2,y2,1]));
L;
```

We define a rational function field that we use to parametrize the exceptional component L with

```{magma}
Q<U>:=FunctionField(Rationals(), 1);
R<y>:=PolynomialRing(Q);
kU<a>:=quo<R | y^2-U-48>;
```

We write down a parametrization of L and check that it satisfies that parametrization. In particular, we see that "V" on Y vanishes on L (we'll see we can use it as a uniformizer at the generic point of L)

```{magma}
Xu:=U;
Yu:=U*a;
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[Xu,Yu]) eq 0};
```

```{magma}
kUV<Vu>:=PowerSeriesRing(kU);
Tu:=Vu+1;
```

```{magma}
R<Ypol>:=PolynomialRing(kUV);
```

Another assumption: We set W to be the function in U that we need and we solve T as a power series in $k( U)[[V]]$ from the equation that we have. If V were not a valid choice as uniformizer, we'd probably fail to solve this equation at this point. Below we just compute all the roots and take the one close to the expression Tu that we already computed (because we know our series for T should specialize to Tu on L for V=0). It would be better to explicitly use newton iteration with initial approximation Tu.

```{magma}
F:=Evaluate(DefiningPolynomial(E), [Xu, Ypol, Tu]);
Fprime:=Derivative(F);
for i in [1..3] do
    Temp:=Yu-Evaluate(F, Yu)/Evaluate(Fprime,Yu);
    Yu:=Temp;
end for;
```

We verify that the power series in $k(U)[[V]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(E),[Xu,Yu,Tu])+O(Vu^(5));
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $V,W,T$ (apologies for the mess-up in naming here: the two $T$s are not the same), and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

#### Patch 1


Here we pick the component L on the first affine patch Y over $((0,1),0)$ of the desingularization $\tilde{E}$ of E, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E,Etilde[4],1);
```

Looking at the equation of $L$ we note that it has no rational points and is geometrically reducible. This means that the residue field $k(L)$ will be of the form $k(u)$ with $k$ some finite extension of $\mathbb{Q}$; in our case $k=\mathbb{Q}(\sqrt{48})=\mathbb{Q}(\sqrt{3})$.

```{magma}
A3<X,V,W>:=Ambient(Y);
L;
```

Note that $L:V^2-48=0, X=0$ has no rational points and is geometrically reducible. In particular, one can work out that the residue field is $\kappa(L)=k(W)$ where $k=\mathbb{Q}(a)$ and $a$ is a square root of $3$. Below we define the extension $k/\mathbb{Q}$ as well as a rational function field that we will use to parametrize the exceptional component L with.

```{magma}
k<a>:=QuadraticField(48);
kU<U>:=FunctionField(k,1);
Wu:=U;
```

```{magma}
kUX<Xu>:=PowerSeriesRing(kU);
```

```{magma}
R<Vpol>:=PolynomialRing(kUX);
```

By definition we have an expression for $X$ and $W$ in $k(U)(Xu)$ as $W=U$ and $X=Xu$. It remains to find an expansion for $V$. From our observations above we note that when taking residues $\overline{V}=4a=4\sqrt{3}\in k(W)$, as we mod out by $V^2-48$, and so we have a first order approximation. Applying Newton iteration gives us enough terms to compute residues.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Xu, Vpol, Wu]);
Fprime:=Derivative(F);
Vu:=4*a;
for i in [1..4] do
    Temp:=Vu-Evaluate(F, Vu)/Evaluate(Fprime,Vu);
    Vu:=Temp;
end for;
```

We verify that the power series $Xu,Vu,Wu$ in $k(U)[[Xu]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Xu,Vu,Wu])+O(Xu^10);
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $X,V,W$, and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Xu, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Xu, Vu, Wu]);
Tu:=Evaluate(DefiningPolynomials(pi)[3], [Xu, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

#### Patch 2


Here we pick the component L on the second affine patch Y over $((0,1),0)$ of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E,Etilde[4],2);
```

Looking at the equation of $L$ we note that it has no rational points and is geometrically reducible. This means that the residue field $k(L)$ will be of the form $k(u)$ with $k$ some finite extension of $\mathbb{Q}$; in our case $k=\mathbb{Q}(\sqrt{48})=\mathbb{Q}(\sqrt{3})$.

```{magma}
A3<X,V,W>:=Ambient(Y);
L;
```

We define the extension $k/\mathbb{Q}$ as well as a rational function field that we will use to parametrize the exceptional component L with.

```{magma}
k<a>:=QuadraticField(48);
kU<U>:=FunctionField(k,1);
Vu:=U;
```

```{magma}
kUX<Xu>:=PowerSeriesRing(kU);
```

```{magma}
R<Wpol>:=PolynomialRing(kUX);
```

By definition we have an expression for $X$ and $W$ in $k(U)(Xu)$ as $W=U$ and $X=Xu$. It remains to find an expansion for $V$. We note that when taking residues we have $\overline{V}=4a=4\sqrt{3}$, as we mod out by $V^2-48$, and so we have a first order approximation. Applying Newton iteration gives us enough terms to compute residues.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Xu, Vu, Wpol]);
Fprime:=Derivative(F);
Wu:=4*a;
for i in [1..4] do
    Temp:=Wu-Evaluate(F, Wu)/Evaluate(Fprime,Wu);
    Wu:=Temp;
end for;
```

We verify that the power series $Xu,Vu,Wu$ in $k(U)[[Xu]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Xu,Vu,Wu])+O(Xu^10);
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $X,V,W$, and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Xu, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Xu, Vu, Wu]);
Tu:=Evaluate(DefiningPolynomials(pi)[3], [Xu, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

#### Patch 3


Here we pick the component L on the third affine patch Y over $(0,0,1)$ of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E,Etilde[4],3);
```

```{magma}
A3<T,V,W>:=Ambient(Y);
L;
```

We write down a parametrization of our conic $L$. For the parametrization below we took the projective closure and projected away from the rational point $[0,0,1]$.

```{magma}
kU<U>:=FunctionField(Rationals(), 1);
Vu:=(-6*U^2-1/8)/(-U^2+1/48)+6;
Wu:=-12*U/(-U^2+1/48);
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[1,Vu,Wu]) eq 0};
```

```{magma}
kUT<Tu>:=PowerSeriesRing(kU);
```

```{magma}
R<Wpol>:=PolynomialRing(kUT);
```

Now we compute an expansion for $W$ in $\mathbb{Q}(U)[[T]]$.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Tu+1, Vu, Wpol]);
Fprime:=Derivative(F);
for i in [1..4] do
    Temp:=Wu-Evaluate(F, Wu)/Evaluate(Fprime,Wu);
    Wu:=Temp;
end for;
```

We verify that the power series $Tu-1,Vu,Wu$ in $k(U)[[Tu]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Tu+1,Vu,Wu])+O(Tu^8);
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $X,V,W$, and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Tu, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Tu, Vu, Wu]);
Tu:=Evaluate(DefiningPolynomials(pi)[3], [Tu, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

### Computing residue at ((0, 0), 3) 


#### Component 1


We unpack some of the desingularization data here. We pick one exceptional component L on a patch Y of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
A2<x2,y2>:=AffinePlane(Rationals());
L:=Curve(A2, Evaluate(DefiningPolynomial(E), [x2,y2,3]));
L;
```

We define a rational function field that we use to parametrize the exceptional component L with

```{magma}
Q<U>:=FunctionField(Rationals(), 1);
R<y>:=PolynomialRing(Q);
kU<a>:=quo<R | y^2-U+144>;
```

We write down a parametrization of L and check that it satisfies that parametrization. In particular, we see that "V" on Y vanishes on L (we'll see we can use it as a uniformizer at the generic point of L)

```{magma}
Xu:=U;
Yu:=U*a;
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[Xu,Yu]) eq 0};
```

```{magma}
kUV<Vu>:=PowerSeriesRing(kU);
Tu:=Vu+3;
```

```{magma}
R<Ypol>:=PolynomialRing(kUV);
```

Another assumption: We set W to be the function in U that we need and we solve T as a power series in $k( U)[[V]]$ from the equation that we have. If V were not a valid choice as uniformizer, we'd probably fail to solve this equation at this point. Below we just compute all the roots and take the one close to the expression Tu that we already computed (because we know our series for T should specialize to Tu on L for V=0). It would be better to explicitly use newton iteration with initial approximation Tu.

```{magma}
F:=Evaluate(DefiningPolynomial(E), [Xu, Ypol, Tu]);
Fprime:=Derivative(F);
for i in [1..3] do
    Temp:=Yu-Evaluate(F, Yu)/Evaluate(Fprime,Yu);
    Yu:=Temp;
end for;
```

We verify that the power series in $k(U)[[V]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(E),[Xu,Yu,Tu])+O(Vu^(5));
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $V,W,T$ (apologies for the mess-up in naming here: the two $T$s are not the same), and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

#### Component 2


We now pick the exceptional component L on the patch Y over $((0, -3), 0)$ of the desingularization $\tilde{E}$ of E, together with the morphism $\pi: Y \to X$.

```{magma}
L,Y,pi:=BlowUpDivisor(E,Etilde[5],1);
A3<X,V,W>:=Ambient(Y);
```

We define a rational function field that we use to parametrize the exceptional component L with

```{magma}
kU<U>:=FunctionField(Rationals(),1);
```

```{magma}
L;
```

Below we find a parametrization of $L$.

```{magma}
Lc,phiL:=Conic(ProjectiveClosure(L));
piL:=Parametrization(Lc);
Q<x, v, w>:=FunctionField(L);
kU<U>:=FunctionField(Domain(piL));
Vu:=Pullback(piL, Pullback(Inverse(phiL), v));
Wu:=Pullback(piL, Pullback(Inverse(phiL), w));
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[0,Vu,Wu]) eq 0};
```

```{magma}
kUX<Xu>:=PowerSeriesRing(kU);
```

```{magma}
R<Wpol>:=PolynomialRing(kUX);
```

Another assumption: We set W to be the function in U that we need and we solve T as a power series in $k( U)[[V]]$ from the equation that we have. If V were not a valid choice as uniformizer, we'd probably fail to solve this equation at this point. Below we just compute all the roots and take the one close to the expression Tu that we already computed (because we know our series for T should specialize to Tu on L for V=0). It would be better to explicitly use newton iteration with initial approximation Tu.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Xu, Vu, Wpol]);
Fprime:=Derivative(F);
for i in [1..4] do
    Temp:=Wu-Evaluate(F, Wu)/Evaluate(Fprime,Wu);
    Wu:=Temp;
end for;
```

We verify that the power series in $k(U)[[V]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Xu,Vu,Wu])+O(Xu^8);
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $V,W,T$ (apologies for the mess-up in naming here: the two $T$s are not the same), and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Xu, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Xu, Vu, Wu]);
Tu:=Evaluate(DefiningPolynomials(pi)[3], [Xu, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, false);
```

### Computing residues at ((3, 0), $\infty$) 


#### Component 1


We unpack some of the desingularization data here. We pick one exceptional component L on a patch Y of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
A2<x2,y2>:=AffinePlane(Rationals());
L:=Curve(A2, Evaluate(DefiningPolynomial(E_inf), [x2,y2,0]));
L;
```

We define a rational function field that we use to parametrize the exceptional component L with

```{magma}
Q<U>:=FunctionField(Rationals(), 1);
R<y>:=PolynomialRing(Q);
kU<a>:=quo<R | y^2-U^3+6*U^2-9*U>;
```

We write down a parametrization of L and check that it satisfies that parametrization. In particular, we see that "V" on Y vanishes on L (we'll see we can use it as a uniformizer at the generic point of L)

```{magma}
Xu:=U;
Yu:=a;
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[Xu,Yu]) eq 0};
```

```{magma}
kUV<Vu>:=PowerSeriesRing(kU);
Tu:=Vu;
```

```{magma}
R<Ypol>:=PolynomialRing(kUV);
```

Another assumption: We set W to be the function in U that we need and we solve T as a power series in $k( U)[[V]]$ from the equation that we have. If V were not a valid choice as uniformizer, we'd probably fail to solve this equation at this point. Below we just compute all the roots and take the one close to the expression Tu that we already computed (because we know our series for T should specialize to Tu on L for V=0). It would be better to explicitly use newton iteration with initial approximation Tu.

```{magma}
F:=Evaluate(DefiningPolynomial(E_inf), [Xu, Ypol, Tu]);
Fprime:=Derivative(F);
for i in [1..3] do
    Temp:=Yu-Evaluate(F, Yu)/Evaluate(Fprime,Yu);
    Yu:=Temp;
end for;
Yu;
```

We verify that the power series in $k(U)[[V]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(E_inf),[Xu,Yu,Tu])+O(Vu^(5));
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,T$ in terms of $V,W,T$ (apologies for the mess-up in naming here: the two $T$s are not the same), and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Tu, true);
```

#### Patch 1


Here we pick the component L on the first affine patch Y over $((3,0),\infty)$ of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E_inf,Etilde_inf[1],1);
```

Looking at the equation of $L$ we note that it has no rational points and is geometrically reducible. This means that the residue field $k(L)$ will be of the form $k(u)$ with $k$ some finite extension of $\mathbb{Q}$; in our case $k=\mathbb{Q}(\sqrt{3})$.

```{magma}
A3<S,V,W>:=Ambient(Y);
L;
```

The variable $S$ corresponds to $1/t$ in our original coordinates.


Note that $L:V^2-3=0, S=0$ has no rational points and is geometrically reducible. In particular, one can work out that the residue field is $\kappa(L)=k(W)$ where $k=\mathbb{Q}(a)$ and $a$ is a square root of $3$. Below we define the extension $k/\mathbb{Q}$ as well as a rational function field that we will use to parametrize the exceptional component L with.

```{magma}
k<a>:=QuadraticField(3);
kU<U>:=FunctionField(k,1);
Wu:=U;
```

```{magma}
kUS<Su>:=PowerSeriesRing(kU);
```

```{magma}
R<Vpol>:=PolynomialRing(kUS);
```

By definition we have an expression for $S$ and $W$ in $k(U)(Su)$ as $W=U$ and $S=Xu$. It remains to find an expansion for $V$. From our observations above we note that when taking residues $\overline{V}=a=\sqrt{3}\in k(W)$, as we mod out by $V^2-3$, and so we have a first order approximation. Applying Newton iteration gives us enough terms to compute residues.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Su, Vpol, Wu]);
Fprime:=Derivative(F);
Vu:=a;
for i in [1..4] do
    Temp:=Vu-Evaluate(F, Vu)/Evaluate(Fprime,Vu);
    Vu:=Temp;
end for;
```

We verify that the power series $Su,Vu,Wu$ in $k(U)[[Su]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Su,Vu,Wu])+O(Su^10);
```

In order to relate all this back to the original coordinates on $E$, we use the description of pi, that expresses $X,Y,T$ in terms of $X,V,W$, and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Su, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Su, Vu, Wu]);
Su:=Evaluate(DefiningPolynomials(pi)[3], [Su, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Su, true);
```

#### Patch 2


Here we pick the component L on the second affine patch Y over $((3,0),\infty)$ of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E_inf,Etilde_inf[1],2);
```

Looking at the equation of $L$ we note that it has no rational points and is geometrically reducible. This means that the residue field $k(L)$ will be of the form $k(u)$ with $k$ some finite extension of $\mathbb{Q}$; in our case $k=\mathbb{Q}(\sqrt{3})$.

```{magma}
A3<S,V,W>:=Ambient(Y);
L;
Factorization(972);
```

Here we see that $L:W^2/972-(V+1/18)^2=0$ and therefore $L$ reducible to the product of two lines over $\mathbb{Q}(\sqrt{972})=\mathbb{Q}(\sqrt{3})$. Thus the residue field $\kappa(L)$ is $\mathbb{Q}(\sqrt{3})(U)$ with $U=V$.

```{magma}
k<a>:=QuadraticField(3);
kU<U>:=FunctionField(k,1);
Vu:=U;
Wu:=(18*Vu+1)*a;
```

```{magma}
kUS<Su>:=PowerSeriesRing(kU);
```

```{magma}
R<Wpol>:=PolynomialRing(kUS);
```

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Su, Vu, Wpol]);
Fprime:=Derivative(F);
for i in [1..4] do
    Temp:=Wu-Evaluate(F, Wu)/Evaluate(Fprime,Wu);
    Wu:=Temp;
end for;
```

We verify that the power series $Su,Vu,Wu$ in $k(U)[[Su]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Su,Vu,Wu])+O(Su^10);
```

In order to relate all this back to the original coordinates on $E$, we use the description of pi, that expresses $X,Y,T$ in terms of $X,V,W$, and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Su, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Su, Vu, Wu]);
Su:=Evaluate(DefiningPolynomials(pi)[3], [Su, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Su, true);
```

#### Patch 3


Here we pick the component L on the third affine patch Y over $(0,0,1)$ of the desingularization $\tilde{E}$ of $E$, together with the morphism $\pi: Y \to E$.

```{magma}
L,Y,pi:=BlowUpDivisor(E_inf,Etilde_inf[1],3);
```

```{magma}
A3<S,V,W>:=Ambient(Y);
L;
```

We write down a parametrization of our conic $L$. For the parametrization below we took the projective closure and projected away from the rational point $[24,0,1]$.

```{magma}
kU<U>:=FunctionField(Rationals(), 1);
Vu:=(24*U^2+8)/(-U^2+1/3);
Wu:=48*U/(-U^2+1/3);
assert forall{f: f in DefiningPolynomials(L) |Evaluate(f,[0,Vu,Wu]) eq 0};
```

```{magma}
kUS<Su>:=PowerSeriesRing(kU);
```

```{magma}
R<Wpol>:=PolynomialRing(kUS);
```

Now we compute an expansion for $W$ in $\mathbb{Q}(U)[[S]]$.

```{magma}
F:=Evaluate(DefiningPolynomial(Y), [Su, Vu, Wpol]);
Fprime:=Derivative(F);
for i in [1..4] do
    Temp:=Wu-Evaluate(F, Wu)/Evaluate(Fprime,Wu);
    Wu:=Temp;
end for;
```

We verify that the power series $Su,Vu,Wu$ in $k(U)[[Tu]]$ that we have computed, indeed satisfy the defining polynomial for $Y$.

```{magma}
Evaluate(DefiningPolynomial(Y),[Su,Vu,Wu])+O(Su^8);
```

In order to relate all this back to the original coordinates on X, we use the description of pi, that expresses $X,Y,S$ in terms of $X,V,W$, and since we have the latter as power series, we can substitute them to get the required results.

```{magma}
Xu:=Evaluate(DefiningPolynomials(pi)[1], [Su, Vu, Wu]);
Yu:=Evaluate(DefiningPolynomials(pi)[2], [Su, Vu, Wu]);
Su:=Evaluate(DefiningPolynomials(pi)[3], [Su, Vu, Wu]);
```

```{magma}
ComputeAllInterestingResidues(Xu, Yu, Su, true);
```

```{magma}

```
